import { Metadata } from "next";
import "../../styles/globals.css";

import { Inter } from 'next/font/google';
// import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '../components/header';
import Footer from '../components/Footer';

import { Analytics } from "@vercel/analytics/react";


const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang='en'>
//       <body className={inter.className}>
//         <ClerkProvider>
//           <Header />
//           {children}
//           <Footer/>
//         </ClerkProvider>
//       </body>
//     </html>
//   );
// }



let title = "Housedesign.ma | Design d'Intérieur IA au Maroc";
let description = "Créez facilement l'intérieur de vos rêves au Maroc avec notre outil d'intelligence artificielle. Design professionnel, simple et abordable. Essayez maintenax@nt !";
let ogimage = "";
let sitename = "HouseDesign";

export const metadata: Metadata = {
  title,
  description,
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    images: [ogimage],
    title,
    description,
    url: "https://roomgpt-demo.vercel.app",
    siteName: sitename,
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    images: [ogimage],
    title,
    description,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       
          {/* Tawk.to Script */}
          <script
            dangerouslySetInnerHTML={{
              __html: `
                var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
                (function(){
                  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
                  s1.async=true;
                  s1.src='https://embed.tawk.to/66853f079d7f358570d68aa6/1i1s7se2i';
                  s1.charset='UTF-8';
                  s1.setAttribute('crossorigin','*');
                  s0.parentNode.insertBefore(s1,s0);
                })();
              `,
            }}
          />
        
      <body className="">
        <ClerkProvider>
        <Header/> 
        {children}
        <Analytics />
        <Footer/>
        </ClerkProvider>
        
      </body>
    </html>
  );
}
